# Generated by Django 3.2.7 on 2021-09-23 17:42

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Myhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=60)),
                ('sample_hood_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Hood_image')),
                ('description', models.TextField()),
                ('police_contacts', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Profile Pic')),
                ('family_name', models.CharField(blank=True, max_length=56)),
                ('gender', models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('mobile', models.CharField(blank=True, max_length=18)),
                ('bio', models.TextField(blank=True, default='Welcome to my world')),
                ('general_location', models.CharField(blank=True, max_length=50)),
                ('hood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hood', to='myhoodApp.myhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pic', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Post_image')),
                ('title', models.CharField(max_length=150, null=True)),
                ('post', tinymce.models.HTMLField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('hood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhoodApp.myhood')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='myhoodApp.profile')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='PolicePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_post', to='myhoodApp.myhood')),
            ],
        ),
        migrations.AddField(
            model_name='myhood',
            name='hood_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhoodApp.profile'),
        ),
        migrations.CreateModel(
            name='HealthFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_facility', to='myhoodApp.myhood')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Business Image')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='myhoodApp.myhood')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='myhoodApp.profile')),
            ],
        ),
    ]
