# Generated by Django 3.2.7 on 2021-09-21 07:26

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=60)),
                ('sample_hood_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Hood_image')),
                ('description', models.TextField()),
                ('health_facilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhoodApp.healthfacilities')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Profile Pic')),
                ('bio', models.TextField(blank=True, default='Welcome to my world')),
                ('gender', models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('general_location', models.CharField(blank=True, max_length=50)),
                ('hood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hood', to='myhoodApp.myhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('post', tinymce.models.HTMLField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood_post', to='myhoodApp.profile')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='myhoodApp.profile')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='PolicePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_post', to='myhoodApp.myhood')),
            ],
        ),
        migrations.AddField(
            model_name='myhood',
            name='hood_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhoodApp.profile'),
        ),
        migrations.AddField(
            model_name='myhood',
            name='hood_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhoodApp.business'),
        ),
        migrations.AddField(
            model_name='myhood',
            name='hood_police_posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhoodApp.policeposts'),
        ),
        migrations.AddField(
            model_name='healthfacilities',
            name='hood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_facility', to='myhoodApp.myhood'),
        ),
        migrations.AddField(
            model_name='business',
            name='hood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='myhoodApp.myhood'),
        ),
    ]
