# Generated by Django 3.2.7 on 2021-09-21 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='phone',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='myhood',
            name='health_facilities',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myhoodApp.healthfacilities'),
        ),
        migrations.AlterField(
            model_name='myhood',
            name='hood_business',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myhoodApp.business'),
        ),
        migrations.AlterField(
            model_name='myhood',
            name='hood_police_posts',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myhoodApp.policeposts'),
        ),
    ]
