# Generated by Django 3.2.7 on 2021-09-21 07:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhoodApp', '0002_auto_20210921_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhood',
            name='sample_hood_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Hood_image'),
        ),
    ]
