# Generated by Django 3.2.7 on 2021-09-21 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhoodApp', '0003_alter_myhood_sample_hood_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhood',
            name='health_facilities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myhoodApp.healthfacilities'),
        ),
        migrations.AlterField(
            model_name='myhood',
            name='hood_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myhoodApp.business'),
        ),
        migrations.AlterField(
            model_name='myhood',
            name='hood_police_posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myhoodApp.policeposts'),
        ),
    ]
