# Generated by Django 3.2.7 on 2021-09-21 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhoodApp', '0004_auto_20210921_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhood',
            name='health_facilities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myhoodApp.healthfacilities'),
        ),
        migrations.AlterField(
            model_name='myhood',
            name='hood_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myhoodApp.profile'),
        ),
        migrations.AlterField(
            model_name='myhood',
            name='hood_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myhoodApp.business'),
        ),
        migrations.AlterField(
            model_name='myhood',
            name='hood_police_posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myhoodApp.policeposts'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myhood', to='myhoodApp.myhood'),
        ),
    ]
