# Generated by Django 3.2.7 on 2021-09-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhoodApp', '0005_auto_20210921_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhood',
            name='health_facilities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myhoodApp.healthfacilities'),
        ),
    ]
