# Generated by Django 3.2.7 on 2021-09-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhoodApp', '0006_alter_myhood_health_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhood',
            name='health_facilities',
        ),
        migrations.RemoveField(
            model_name='myhood',
            name='hood_business',
        ),
        migrations.RemoveField(
            model_name='myhood',
            name='hood_police_posts',
        ),
    ]
