# Generated by Django 3.2.7 on 2021-09-21 10:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhoodApp', '0007_auto_20210921_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='post_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Post_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Profile Pic'),
        ),
    ]
