# Generated by Django 3.2.7 on 2021-09-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhoodApp', '0008_auto_20210921_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myhoodApp.profile'),
        ),
    ]
