# Generated by Django 3.2.7 on 2021-09-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhoodApp', '0010_alter_userpost_hood'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='family_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
