# Generated by Django 3.2.7 on 2021-09-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhoodApp', '0011_auto_20210921_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family_name',
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
