# Generated by Django 3.2.7 on 2021-09-21 14:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhoodApp', '0012_alter_profile_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='biz_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Business Image'),
        ),
    ]
