# Generated by Django 3.2.7 on 2021-09-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhoodApp', '0014_business_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhood',
            name='police_contacts',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
